#!/usr/bin/env bash

build() {
  add_binary /usr/bin/btrfs
  add_binary /usr/bin/mount
  add_binary /usr/bin/mountpoint
  add_binary /usr/bin/umount
  add_binary /usr/bin/sync
  add_binary /usr/bin/mv
  add_binary /usr/bin/sleep

  add_file /usr/lib/cachy-freeze/cachy-freeze-reset
  add_file /etc/cachy-freeze-initrd.conf
  add_systemd_unit cachy-freeze-reset.service

  add_symlink \
    /usr/lib/systemd/system/initrd-root-fs.target.requires/cachy-freeze-reset.service \
    /usr/lib/systemd/system/cachy-freeze-reset.service
}

help() {
  cat <<'EOF'
Adds the CachyOS Btrfs frozen-root reset service to a systemd initramfs.
EOF
}
