# Installed as /etc/cachy-freeze.conf
STATE_DIR=/var/lib/cachy-freeze
TOP_MOUNT=/run/cachy-freeze/btrfs
MAINTENANCE_SUBVOL=@
GOLDEN_SUBVOL=@golden
ACTIVE_SUBVOL=@active
PREVIOUS_SUBVOL=@active.previous
NEXT_SUBVOL=@active.next
ROOT_UUID=
