#!/usr/bin/env bash
set -Eeuo pipefail

readonly CONFIG=/etc/cachy-employee.conf
[[ -r $CONFIG ]] || exit 0
# shellcheck disable=SC1090
source "$CONFIG"

[[ $EMPLOYEE_USER =~ ^[a-z][a-z0-9_-]{1,31}$ ]] || exit 1
template="/var/lib/cachy-employee-template/$EMPLOYEE_USER"
home=$(getent passwd "$EMPLOYEE_USER" | cut -d: -f6)
[[ -d $template && -n $home && -d $home ]] || exit 1

rsync -aHAX --delete "$template/" "$home/"
chown -R "$EMPLOYEE_USER:$EMPLOYEE_USER" "$home"

